export const content = {
    uz: {
        city: 'Shahar:',
        savol_javoblar: 'Savol-javoblar',
        punkt: 'Savol-javoblar',
        dostavka: 'Buyurtmangizni 1 kunda bepul yetkazib beramiz!',
        buyurtmalarim: 'Buyurtmalarim',
        kirish: 'Kirish',
        saralangan: 'Saralangan',
        savat: 'Savat',
        nasiya: 'Halol nasiya',
        elect: 'Elektronika',
        maishiy: 'Maishiy texnika',
        kiyim: 'Kiyim',      
        poyabzal: 'Poyabzallar',
        aksessuar: 'Aksessuarlar',
        goʻzallik: 'Goʻzallik',
        salomatlik: 'Salomatlik', 
        rozgor: 'Uy-roʻzgʻor buyumlari',
        qurilish: 'Qurilish va taʼmirlash',
        avtotovar: 'Avtotovarlar',
        yana: 'Yana',
  
    },
    ru: {
        city: 'Город:',
        savol_javoblar: 'Вопросы и ответы',
        punkt: 'Пункты доставки',
        dostavka: 'Доставим ваш заказ бесплатно за 1 день!',
        buyurtmalarim: 'Мои заказы',
        kirish: 'Входить',
        saralangan: 'Сортировка',
        savat: 'Корзина',
        nasiya: 'Халяльная рассрочка',
        elect: 'Электроника',
        maishiy: 'Бытовая техника',
        kiyim: 'Одежда',
        poyabzal: 'Обувь',
        aksessuar: 'Аксессуары',
        goʻzallik: 'Красота',
        salomatlik: 'Здоровье',
        rozgor: 'Домашние товары',
        qurilish: 'Строительство и ремонт',
        avtotovar: 'Автотовары',
        yana: 'Еще',
    },
}